import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from 'sonner'
import { NextProgress } from "@/components/shared/next-progress";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Tablero",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es">
            <body className={inter.className}>
                <Toaster expand={false}/>
                <NextProgress />
                <ThemeProvider attribute="class">
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
